In [18]:
'''
建立一個外觀 (9, 9) 的 ndarray 並且填入九九乘法表（hw301.py）
'''
import numpy as np
i = np.arange(1,10)
j = i
i = np.array(i)
j = np.array(j)
for n in i:
    ans = n*j
    print ans

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[ 3  6  9 12 15 18 21 24 27]
[ 4  8 12 16 20 24 28 32 36]
[ 5 10 15 20 25 30 35 40 45]
[ 6 12 18 24 30 36 42 48 54]
[ 7 14 21 28 35 42 49 56 63]
[ 8 16 24 32 40 48 56 64 72]
[ 9 18 27 36 45 54 63 72 81]


In [38]:
'''
利用 numpy 提供的 .size 屬性、.sum() 方法、.mean() 方法與 .sqrt() 實作樣本標準差函數（hw302.py）
'''
import numpy as np
aList = [13,67,34,91,2,55,-1]
aList = np.array(aList)
ans = np.sqrt(np.sum((aList-np.mean(aList))**2)/(np.size(aList)-1))
print ans


35.1032490695
